### PR TITLE
Resolve fatal error "Too few arguments to function VIP_Filesystem_Stream_Wrapper::string_to_resource()"

### LINKED ISSUE #1347: Too few arguments to function Automattic\VIP\Files\VIP_Filesystem_Stream_Wrapper::string_to_resource()
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Automattic\VIP\Files\VIP_Filesystem_Stream_Wrapper::string_to_resource(), 1 passed in /var/www/wp-content/mu-plugins/files/class-vip-filesystem-stream-wrapper.php on line 547 and exactly 2 expected in /var/www/wp-content/mu-plugins/files/class-vip-filesystem-stream-wrapper.php:650
```

Looks like https://github.com/Automattic/vip-go-mu-plugins/blob/1aedce600165b5cd5af82d6fb0647a64dd8ff19a/files/class-vip-filesystem-stream-wrapper.php#L547 is missing the second parameter (introduced in https://github.com/Automattic/vip-go-mu-plugins/pull/1337/files).

### PR DESCRIPTION
**Pull request by rebeccahum**
## Description

Resolves #1347

### CODE REVIEW

**Comment by nickdaugherty** [comment]
r682-stacks
